//import { User, Vehicle, PremiumOption } from "@/types";

// Marques par type de véhicule
export const brandsByVehicleType = {
  // Voitures
  voiture: [
    "ABARTH",
    "ALFA ROMEO",
    "ALPINE",
    "AUDI",
    "BENTLEY",
    "BMW",
    "BYD",
    "CADILLAC",
    "CHEVROLET",
    "CHRYSLER",
    "CITROEN",
    "CUPRA",
    "DACIA",
    "DS AUTOMOBILES",
    "FERRARI",
    "FIAT",
    "FORD",
    "HONDA",
    "HYUNDAI",
    "INFINITI",
    "JAGUAR",
    "JEEP",
    "KIA",
    "LAMBORGHINI",
    "LANCIA",
    "LAND ROVER",
    "LEXUS",
    "LIGIER",
    "LOTUS",
    "MASERATI",
    "MAZDA",
    "MCLAREN",
    "MERCEDES",
    "MG",
    "MINI",
    "MITSUBISHI",
    "NISSAN",
    "OPEL",
    "PEUGEOT",
    "POLESTAR",
    "PORSCHE",
    "RENAULT",
    "ROLLS ROYCE",
    "SEAT",
    "SKODA",
    "SMART",
    "SSANGYONG",
    "SUBARU",
    "SUZUKI",
    "TESLA",
    "TOYOTA",
    "VOLKSWAGEN",
    "VOLVO",
    "AUTRE MARQUE",
  ],

  utilitaire: [
    "CITROEN",
    "FIAT",
    "FORD",
    "IVECO",
    "MAN",
    "MAXUS",
    "MERCEDES BENZ",
    "NISSAN",
    "OPEL",
    "PEUGEOT",
    "RENAULT",
    "TOYOTA",
    "VOLKSWAGEN",
    "AUTRES UTILITAIRES",
  ],

  caravane: [
    "ADRIA",
    "BURSTNER",
    "CARAVELAIR",
    "CHAUSSON",
    "DETHLEFFS",
    "ERIBA",
    "FENDT",
    "HOBBY",
    "HYMER",
    "KNAUS",
    "LMC",
    "RAPIDO",
    "STERCKEMAN",
    "TABBERT",
    "TRIGANO",
    "WEINSBERG",
    "WILK",
    "AUTRES CARAVANES",
  ],

  remorque: [
    "ANSSEMS",
    "BOCKMANN",
    "BRENDERUP",
    "HAPERT",
    "HUMBAUR",
    "LIDER",
    "MARTZ",
    "NORAUTO",
    "SARIS",
    "TRIGANO",
    "UNSINN",
    "AUTRES REMORQUES",
  ],

  moto: [
    "APRILIA",
    "BENELLI",
    "BETA",
    "BMW",
    "BRIXTON",
    "CFMOTO",
    "DAELIM",
    "DERBI",
    "DUCATI",
    "ENERGICA",
    "FANTIC",
    "GASGAS",
    "HARLEY DAVIDSON",
    "HONDA",
    "HUSABERG",
    "HUSQVARNA",
    "INDIAN",
    "KAWASAKI",
    "KEEWAY",
    "KTM",
    "KYMCO",
    "MASH",
    "MBK",
    "MOTO GUZZI",
    "MV AGUSTA",
    "NORTON",
    "ORCAL",
    "PEUGEOT",
    "PIAGGIO",
    "QUADRO",
    "RIEJU",
    "ROYAL ENFIELD",
    "SHERCO",
    "SUZUKI",
    "SWM",
    "SYM",
    "TGB",
    "TRIUMPH",
    "VESPA",
    "VICTORY",
    "YAMAHA",
    "ZONTES",
    "ZUNDAPP",
    "AUTRES MOTOS",
  ],

  scooter: [
    "APRILIA",
    "BAOTIAN",
    "BMW",
    "DERBI",
    "GILERA",
    "HONDA",
    "KEEWAY",
    "KYMCO",
    "MBK",
    "PEUGEOT",
    "PIAGGIO",
    "SYM",
    "VESPA",
    "YAMAHA",
    "ZONTES",
    "AUTRE SCOOTER",
  ],

  quad: [
    "AEON",
    "ACCESS MOTOR",
    "ARCTIC CAT",
    "CAN AM",
    "CFMOTO",
    "GOES",
    "HONDA",
    "HYTRACK",
    "KAWASAKI",
    "KYMCO",
    "LINHAI",
    "POLARIS",
    "SUZUKI",
    "TGB",
    "YAMAHA",
    "AUTRES QUADS",
  ],

  jetski: ["BOMBARDIER", "KAWASAKI", "SEA DOO", "YAMAHA", "AUTRES JETSKI"],

  bateau: [
    "ANTARES",
    "BAYLINER",
    "BENETEAU",
    "BOMBARD",
    "CAP CAMARAT",
    "FLYER",
    "JEANNEAU",
    "OCQUETEAU",
    "PACIFIC CRAFT",
    "QUICKSILVER",
    "RANIERI",
    "SEA RAY",
    "SELVA",
    "WHITE SHARK",
    "ZODIAC",
    "AUTRES BATEAUX",
  ],

  aerien: [
    "ADVANCE",
    "AIRBORNE",
    "BGD",
    "DUDEK",
    "GIN",
    "NOVA",
    "OZONE",
    "SKYWALK",
    "SWING",
    "UP",
    "AUTRES AERIENS",
  ],

  // Services (pas de marques spécifiques)
  reparation: [],
  remorquage: [],
  entretien: [],
  "autre-service": [],

  // Pièces détachées (utilise toutes les marques)
  "piece-moto": [
    "APRILIA",
    "BENELLI",
    "BETA",
    "BMW",
    "BRIXTON",
    "CFMOTO",
    "DAELIM",
    "DERBI",
    "DUCATI",
    "ENERGICA",
    "FANTIC",
    "GASGAS",
    "HARLEY DAVIDSON",
    "HONDA",
    "HUSABERG",
    "HUSQVARNA",
    "INDIAN",
    "KAWASAKI",
    "KEEWAY",
    "KTM",
    "KYMCO",
    "MASH",
    "MBK",
    "MOTO GUZZI",
    "MV AGUSTA",
    "NORTON",
    "ORCAL",
    "PEUGEOT",
    "PIAGGIO",
    "QUADRO",
    "RIEJU",
    "ROYAL ENFIELD",
    "SHERCO",
    "SUZUKI",
    "SWM",
    "SYM",
    "TGB",
    "TRIUMPH",
    "VESPA",
    "VICTORY",
    "YAMAHA",
    "ZONTES",
    "ZUNDAPP",
    "AUTRES MOTOS",
  ],

  "piece-voiture": [
    "ABARTH",
    "AC",
    "ALFA ROMEO",
    "ALPINA",
    "ALPINE",
    "ASTON MARTIN",
    "AUDI",
    "AUSTIN",
    "AUSTIN HEALEY",
    "BAIC",
    "BENTLEY",
    "BMW",
    "BORGWARD",
    "BUICK",
    "BYD",
    "CADILLAC",
    "CHEVROLET",
    "CHRYSLER",
    "CITROEN",
    "CUPRA",
    "DACIA",
    "DFSK",
    "DODGE",
    "DONKERVOORT",
    "DS AUTOMOBILES",
    "FERRARI",
    "FIAT",
    "FORD",
    "FORTHING",
    "FOTON",
    "GMC",
    "GLAS",
    "HONDA",
    "HUMMER",
    "HYUNDAI",
    "INEOS",
    "INFINITI",
    "ISUZU",
    "JAC",
    "JAECOO",
    "JAGUAR",
    "JEEP",
    "KIA",
    "KTM",
    "LADA",
    "LAMBORGHINI",
    "LANCIA",
    "LAND ROVER",
    "LEXUS",
    "LIGIER",
    "LIVAN",
    "LONDON TAXI",
    "LOTUS",
    "MAN",
    "MASERATI",
    "MAXUS",
    "MAYBACH",
    "MAZDA",
    "MCLAREN",
    "MERCEDES BENZ",
    "MG",
    "MINI",
    "MITSUBISHI",
    "MORGAN",
    "NISSAN",
    "OLDSMOBILE",
    "OPEL",
    "PACKARD",
    "PEUGEOT",
    "PLYMOUTH",
    "POLARIS",
    "POLESTAR",
    "PONTIAC",
    "PORSCHE",
    "RENAULT",
    "ROLLS ROYCE",
    "ROVER",
    "SAAB",
    "SEAT",
    "SKODA",
    "SMART",
    "SSANGYONG",
    "SUBARU",
    "SUZUKI",
    "SWM",
    "TESLA",
    "TOYOTA",
    "TRIUMPH",
    "VOLKSWAGEN",
    "VOLVO",
    "WESTFIELD",
    "WIESMANN",
    "XPENG",
    "ZASTAVA",
    "AUTRES VOITURES",
  ],

  "autre-piece": [
    "ANTIVOL",
    "BAGAGERIE",
    "CASQUES",
    "COMBINAISONS",
    "GANTS",
    "HUILES",
    "OUTILS",
    "PNEUMATIQUES",
    "AUTRES PIECES",
  ],
};

// Modèles de voitures populaires avec dropdown dynamique
export const carModelsByBrand = {
  BMW: [
    "SERIE 1",
    "SERIE 2",
    "SERIE 3",
    "SERIE 4",
    "SERIE 5",
    "SERIE 6",
    "SERIE 7",
    "SERIE 8",
    "X1",
    "X2",
    "X3",
    "X4",
    "X5",
    "X6",
    "X7",
    "Z4",
    "I3",
    "I4",
    "IX",
    "IX3",
    "114D",
    "116D",
    "118D",
    "120D",
    "220D",
    "320D",
    "330D",
    "520D",
    "530D",
    "AUTRE BMW",
  ],
  "MERCEDES BENZ": [
    "CLASSE A",
    "CLASSE B",
    "CLASSE C",
    "CLASSE E",
    "CLASSE S",
    "CLA",
    "CLS",
    "GLA",
    "GLB",
    "GLC",
    "GLE",
    "GLS",
    "AMG GT",
    "EQA",
    "EQB",
    "EQC",
    "EQS",
    "A180",
    "A200",
    "C180",
    "C200",
    "C220D",
    "E200",
    "E220D",
    "AUTRE MERCEDES",
  ],
  AUDI: [
    "A1",
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "Q2",
    "Q3",
    "Q5",
    "Q7",
    "Q8",
    "TT",
    "R8",
    "E TRON GT",
    "30 TFSI",
    "35 TFSI",
    "40 TFSI",
    "45 TFSI",
    "50 TFSI",
    "AUTRE AUDI",
  ],
  PEUGEOT: [
    "108",
    "208",
    "2008",
    "308",
    "3008",
    "408",
    "508",
    "5008",
    "PARTNER",
    "RIFTER",
    "TRAVELLER",
    "E 208",
    "E 2008",
    "E 308",
    "AUTRE PEUGEOT",
  ],
  RENAULT: [
    "TWINGO",
    "CLIO",
    "CAPTUR",
    "MEGANE",
    "SCENIC",
    "KADJAR",
    "KOLEOS",
    "TALISMAN",
    "ZOE",
    "KANGOO",
    "TRAFIC",
    "MASTER",
    "DUSTER",
    "SANDERO",
    "LOGAN",
    "AUTRE RENAULT",
  ],
  TOYOTA: [
    "AYGO",
    "YARIS",
    "COROLLA",
    "CAMRY",
    "PRIUS",
    "CHR",
    "RAV4",
    "HIGHLANDER",
    "LAND CRUISER",
    "PROACE",
    "HILUX",
    "AUTRE TOYOTA",
  ],
  VOLKSWAGEN: [
    "UP",
    "POLO",
    "GOLF",
    "JETTA",
    "PASSAT",
    "ARTEON",
    "T CROSS",
    "T ROC",
    "TIGUAN",
    "TOURAN",
    "TOUAREG",
    "ID 3",
    "ID 4",
    "ID BUZZ",
    "AUTRE VOLKSWAGEN",
  ],
  FORD: [
    "KA",
    "FIESTA",
    "FOCUS",
    "MONDEO",
    "MUSTANG",
    "ECOSPORT",
    "KUGA",
    "EDGE",
    "EXPLORER",
    "TRANSIT",
    "RANGER",
    "AUTRE FORD",
  ],
  DACIA: [
    "SPRING",
    "SANDERO",
    "SANDERO STEPWAY",
    "LOGAN",
    "DUSTER",
    "JOGGER",
    "AUTRE DACIA",
  ],
  OPEL: [
    "ADAM",
    "CORSA",
    "ASTRA",
    "INSIGNIA",
    "MOKKA",
    "CROSSLAND",
    "GRANDLAND",
    "ZAFIRA",
    "VIVARO",
    "MOVANO",
    "AUTRE OPEL",
  ],
  NISSAN: [
    "MICRA",
    "NOTE",
    "LEAF",
    "JUKE",
    "QASHQAI",
    "X TRAIL",
    "NAVARA",
    "TOWNSTAR",
    "AUTRE NISSAN",
  ],
  HYUNDAI: [
    "I10",
    "I20",
    "I30",
    "KONA",
    "TUCSON",
    "SANTA FE",
    "IONIQ",
    "IONIQ 5",
    "IONIQ 6",
    "AUTRE HYUNDAI",
  ],
  KIA: [
    "PICANTO",
    "RIO",
    "CEED",
    "SPORTAGE",
    "SORENTO",
    "STONIC",
    "NIRO",
    "EV6",
    "EV9",
    "AUTRE KIA",
  ],
  FIAT: [
    "PANDA",
    "500",
    "500X",
    "500L",
    "TIPO",
    "PUNTO",
    "DOBLO",
    "SCUDO",
    "FIORINO",
    "AUTRE FIAT",
  ],
  SKODA: [
    "FABIA",
    "SCALA",
    "OCTAVIA",
    "SUPERB",
    "KAMIQ",
    "KAROQ",
    "KODIAQ",
    "ENYAQ",
    "AUTRE SKODA",
  ],
  SEAT: [
    "IBIZA",
    "LEON",
    "ATECA",
    "ARONA",
    "TARRACO",
    "ALHAMBRA",
    "AUTRE SEAT",
  ],
  MINI: [
    "MINI 3 PORTES",
    "MINI 5 PORTES",
    "CLUBMAN",
    "CABRIO",
    "COUNTRYMAN",
    "PACEMAN",
    "AUTRE MINI",
  ],
  VOLVO: [
    "C30",
    "C40",
    "S60",
    "S90",
    "V40",
    "V60",
    "V90",
    "XC40",
    "XC60",
    "XC90",
    "AUTRE VOLVO",
  ],
  SUZUKI: [
    "SWIFT",
    "IGNIS",
    "BALENO",
    "VITARA",
    "S CROSS",
    "JIMNY",
    "AUTRE SUZUKI",
  ],
  MAZDA: [
    "MAZDA2",
    "MAZDA3",
    "MAZDA6",
    "CX 3",
    "CX 30",
    "CX 5",
    "CX 60",
    "MX 5",
    "AUTRE MAZDA",
  ],
  SUBARU: ["IMPREZA", "XV", "FORESTER", "OUTBACK", "BRZ", "AUTRE SUBARU"],
  TESLA: [
    "MODEL 3",
    "MODEL Y",
    "MODEL S",
    "MODEL X",
    "CYBERTRUCK",
    "AUTRE TESLA",
  ],
  LEXUS: [
    "CT",
    "IS",
    "ES",
    "GS",
    "UX",
    "NX",
    "RX",
    "RZ",
    "GX",
    "LX",
    "AUTRE LEXUS",
  ],
  JAGUAR: [
    "XE",
    "XF",
    "XJ",
    "F TYPE",
    "E PACE",
    "F PACE",
    "I PACE",
    "AUTRE JAGUAR",
  ],
  "LAND ROVER": [
    "DEFENDER",
    "DISCOVERY",
    "DISCOVERY SPORT",
    "RANGE ROVER",
    "RANGE ROVER SPORT",
    "RANGE ROVER VELAR",
    "RANGE ROVER EVOQUE",
    "AUTRE LAND ROVER",
  ],
  "ALFA ROMEO": [
    "MITO",
    "GIULIETTA",
    "GIULIA",
    "STELVIO",
    "TONALE",
    "AUTRE ALFA ROMEO",
  ],
  JEEP: [
    "RENEGADE",
    "COMPASS",
    "CHEROKEE",
    "GRAND CHEROKEE",
    "WRANGLER",
    "GLADIATOR",
    "AUTRE JEEP",
  ],
  MITSUBISHI: [
    "SPACE STAR",
    "COLT",
    "LANCER",
    "ASX",
    "ECLIPSE CROSS",
    "OUTLANDER",
    "PAJERO",
    "L200",
    "AUTRE MITSUBISHI",
  ],
  PORSCHE: [
    "911",
    "718 BOXSTER",
    "718 CAYMAN",
    "PANAMERA",
    "TAYCAN",
    "MACAN",
    "CAYENNE",
    "AUTRE PORSCHE",
  ],
  FERRARI: [
    "458 ITALIA",
    "488 GTB",
    "F8 TRIBUTO",
    "ROMA",
    "PORTOFINO",
    "SF90 STRADALE",
    "296 GTB",
    "AUTRE FERRARI",
  ],
  MASERATI: [
    "GHIBLI",
    "QUATTROPORTE",
    "LEVANTE",
    "GRECALE",
    "MC20",
    "AUTRE MASERATI",
  ],
  "ROLLS ROYCE": [
    "PHANTOM",
    "GHOST",
    "WRAITH",
    "DAWN",
    "CULLINAN",
    "SPECTRE",
    "AUTRE ROLLS ROYCE",
  ],
  BENTLEY: ["CONTINENTAL GT", "FLYING SPUR", "BENTAYGA", "AUTRE BENTLEY"],
  MCLAREN: [
    "540C",
    "570S",
    "600LT",
    "720S",
    "765LT",
    "ARTURA",
    "P1",
    "SPEEDTAIL",
    "AUTRE MCLAREN",
  ],
  ABARTH: ["500", "595", "695", "124 SPIDER", "AUTRE ABARTH"],
  ALPINE: ["A110", "AUTRE ALPINE"],
  CUPRA: ["BORN", "FORMENTOR", "ATECA", "LEON", "AUTRE CUPRA"],
  "DS AUTOMOBILES": ["DS 3", "DS 4", "DS 5", "DS 7", "DS 9", "AUTRE DS"],
  LANCIA: ["YPSILON", "AUTRE LANCIA"],
  LIGIER: ["JS50", "JS60", "JS2", "AUTRE LIGIER"],
  MG: ["MG3", "MG4", "MG5", "ZS", "HS", "MARVEL R", "EHS", "AUTRE MG"],
  POLESTAR: [
    "POLESTAR 1",
    "POLESTAR 2",
    "POLESTAR 3",
    "POLESTAR 4",
    "AUTRE POLESTAR",
  ],
  BYD: ["ATTO 3", "DOLPHIN", "SEAL", "TANG", "HAN", "AUTRE BYD"],
  SMART: ["FORTWO", "FORFOUR", "HASHTAG 1", "HASHTAG 3", "AUTRE SMART"],
  CITROEN: [
    "C1",
    "C3",
    "C3 AIRCROSS",
    "C3 PICASSO",
    "C4",
    "C4 CACTUS",
    "C5",
    "C5 AIRCROSS",
    "BERLINGO",
    "SPACETOURER",
    "JUMPY",
    "JUMPER",
    "E C4",
    "AMI",
    "AUTRE CITROEN",
  ],
};

// Fonction utilitaire pour obtenir les marques selon la sous-catégorie
export const getBrandsBySubcategory = (subcategory: string): string[] => {
  return (
    brandsByVehicleType[subcategory as keyof typeof brandsByVehicleType] || []
  );
};
export const fuelTypes = [
  { value: "gasoline", label: "Essence" },
  { value: "diesel", label: "Diesel" },
  { value: "electric", label: "Électrique" },
  { value: "hybrid", label: "Hybride" },
];

export const conditions = [
  { value: "used", label: "Occasion" },
  { value: "damaged", label: "Accidenté" },
];

// Équipements prédéfinis pour les véhicules
export const VEHICLE_EQUIPMENT = {
  voiture: [
    "Toit ouvrant / Toit panoramique",
    "Climatisation",
    "GPS",
    "Sièges chauffants",
    "Caméra de recul",
    "Radar de recul",
    "Jantes alliage",
    "Feux LED / Xénon",
    "Vitres électriques",
    "Airbags",
    "Sièges électriques",
    "Attelage",
    "Régulateur de vitesse",
    "Bluetooth",
    "Système audio premium",
    "Cuir",
  ],
  moto: [
    "ABS",
    "Contrôle de traction",
    "Modes de conduite",
    "Éclairage LED",
    "Quickshifter",
    "Chauffage poignées",
    "Pare-brise",
    "Top case",
    "Sacoches",
    "Antivol",
    "Compteur digital",
    "USB",
  ],
  scooter: [
    "ABS",
    "Contrôle de traction",
    "Modes de conduite",
    "Éclairage LED",
    "Chauffage poignées",
    "Pare-brise",
    "Top case",
    "Coffre sous la selle",
    "Antivol",
    "Compteur digital",
    "USB",
    "Prise 12V",
  ],
  utilitaire: [
    "Climatisation",
    "GPS",
    "Caméra de recul",
    "Radar de recul",
    "Attelage",
    "Cloison de séparation",
    "Hayon arrière",
    "Porte latérale",
    "Plancher bois",
    "Éclairage LED cargo",
    "Prise 12V",
    "Radio Bluetooth",
  ],
  quad: [
    "Direction assistée",
    "Suspension ajustable",
    "Treuil électrique",
    "Feux LED",
    "Prise 12V",
    "Porte-bagages",
    "Protection inférieure",
    "Poignées chauffantes",
    "Compteur digital",
  ],
  jetski: [
    "Système de freinage",
    "Mode économique",
    "Système audio",
    "Compartiment étanche",
    "Échelle de remontée",
    "Tapis antidérapant",
  ],
  bateau: [
    "GPS/Sondeur",
    "VHF",
    "Pilote automatique",
    "Guindeau électrique",
    "Bimini",
    "Taud de soleil",
    "Annexe",
    "Moteur auxiliaire",
    "Réfrigérateur",
    "WC marin",
  ],
  aerien: [
    "Parachute de secours",
    "Variomètre",
    "GPS",
    "Radio",
    "Sellette",
    "Casque",
    "Protection dorsale",
  ],
};

export const colors = [
  "#ef4444", // red
  "#f97316", // orange
  "#eab308", // yellow
  "#22c55e", // green
  "#06b6d4", // cyan
  "#3b82f6", // blue
  "#8b5cf6", // violet
  "#ec4899", // pink
  "#64748b", // slate
  "#6b7280", // gray
];

// Nombre de portes pour les véhicules
export const doorCounts = [
  { value: 2, label: "2 portes" },
  { value: 3, label: "3 portes" },
  { value: 4, label: "4 portes" },
  { value: 5, label: "5 portes" },
];

// Types de véhicules
export const vehicleTypes = [
  { value: "citadine", label: "Citadine" },
  { value: "berline", label: "Berline" },
  { value: "suv", label: "SUV" },
  { value: "break", label: "Break" },
  { value: "coupe", label: "Coupé" },
  { value: "cabriolet", label: "Cabriolet" },
  { value: "monospace", label: "Monospace" },
  { value: "pickup", label: "Pick-up" },
];

// Types de transmission
export const transmissionTypes = [
  { value: "manual", label: "Manuelle" },
  { value: "automatic", label: "Automatique" },
  { value: "semi-automatic", label: "Semi-automatique" },
];

// Couleurs de véhicules
export const vehicleColors = [
  { value: "blanc", label: "Blanc" },
  { value: "noir", label: "Noir" },
  { value: "gris", label: "Gris" },
  { value: "argent", label: "Argent" },
  { value: "rouge", label: "Rouge" },
  { value: "bleu", label: "Bleu" },
  { value: "vert", label: "Vert" },
  { value: "jaune", label: "Jaune" },
  { value: "orange", label: "Orange" },
  { value: "violet", label: "Violet" },
  { value: "marron", label: "Marron" },
  { value: "beige", label: "Beige" },
];

// Types de sellerie
export const upholsteryTypes = [
  { value: "tissu", label: "Tissu" },
  { value: "cuir_partiel", label: "Cuir partiel" },
  { value: "cuir", label: "Cuir" },
  { value: "velours", label: "Velours" },
  { value: "alcantara", label: "Alcantara" },
];

// Classes d'émission
export const emissionClasses = [
  { value: "euro1", label: "Euro 1" },
  { value: "euro2", label: "Euro 2" },
  { value: "euro3", label: "Euro 3" },
  { value: "euro4", label: "Euro 4" },
  { value: "euro5", label: "Euro 5" },
  { value: "euro6", label: "Euro 6" },
];

// Types d'utilitaires
export const utilityTypes = [
  { value: "van", label: "Fourgon" },
  { value: "truck", label: "Camion" },
  { value: "pickup", label: "Pick-up" },
  { value: "trailer", label: "Remorque" },
];

// Types de caravanes
export const caravanTypes = [
  { value: "travel_trailer", label: "Caravane de voyage" },
  { value: "motorhome", label: "Camping-car" },
  { value: "popup", label: "Caravane pliante" },
  { value: "fifth_wheel", label: "Caravane à sellette" },
];

// Types de remorques
export const trailerTypes = [
  { value: "utility", label: "Utilitaire" },
  { value: "boat", label: "Porte-bateau" },
  { value: "car", label: "Porte-voiture" },
  { value: "cargo", label: "Cargo fermée" },
];

// Types de motos
export const motorcycleTypes = [
  { value: "sport", label: "Sportive" },
  { value: "touring", label: "Routière" },
  { value: "urban", label: "Urbaine" },
  { value: "trail", label: "Trail" },
  { value: "custom", label: "Custom" },
  { value: "roadster", label: "Roadster" },
  { value: "enduro", label: "Enduro" },
  { value: "cross", label: "Cross" },
];

// Types de quads
export const quadTypes = [
  { value: "sport", label: "Sport" },
  { value: "utility", label: "Utilitaire" },
  { value: "touring", label: "Tourisme" },
  { value: "youth", label: "Jeune" },
];

// Types de jetskis
export const jetskiTypes = [
  { value: "recreation", label: "Loisir" },
  { value: "performance", label: "Performance" },
  { value: "luxury", label: "Luxe" },
  { value: "touring", label: "Tourisme" },
];

// Types de bateaux
export const boatTypes = [
  { value: "motor", label: "Bateau à moteur" },
  { value: "sailing", label: "Voilier" },
  { value: "fishing", label: "Bateau de pêche" },
  { value: "inflatable", label: "Pneumatique" },
  { value: "cabin", label: "Cabine" },
];

// Types de services
export const serviceTypes = [
  { value: "repair", label: "Réparation" },
  { value: "maintenance", label: "Entretien" },
  { value: "towing", label: "Remorquage" },
  { value: "inspection", label: "Contrôle technique" },
  { value: "bodywork", label: "Carrosserie" },
  { value: "painting", label: "Peinture" },
  { value: "tuning", label: "Préparation" },
];

// Types de véhicules par sous-catégorie
export const VEHICLE_TYPES = {
  voiture: [
    "Citadine",
    "Berline",
    "SUV",
    "Break",
    "Coupé",
    "Cabriolet",
    "Monospace",
    "Pick-up",
    "Autre voiture",
  ],
  utilitaire: [
    "Fourgon",
    "Camionnette",
    "Camion",
    "Pick-up",
    "Autre utilitaire",
  ],
  caravane: [
    "Caravane de voyage",
    "Camping-car",
    "Caravane pliante",
    "Caravane à sellette",
    "Autre caravane",
  ],
  remorque: [
    "Utilitaire",
    "Porte-bateau",
    "Porte-voiture",
    "Cargo fermée",
    "Autre remorque",
  ],
  moto: [
    "Sportive",
    "Routière",
    "Urbaine",
    "Trail",
    "Custom",
    "Roadster",
    "Cross",
    "Enduro",
    "Autre moto",
  ],
  scooter: [
    "50cm³",
    "125cm³",
    "300cm³",
    "Maxi-scooter",
    "Électrique",
    "Autre scooter",
  ],
  quad: ["Sport", "Utilitaire", "Loisir", "Enfant", "Autre quad"],
  jetski: ["Loisir", "Performance", "Luxe", "Tourisme", "Autre jetski"],
  bateau: [
    "Bateau à moteur",
    "Voilier",
    "Bateau de pêche",
    "Pneumatique",
    "Cabine",
    "Autre bateau",
  ],
  aerien: [
    "ULM",
    "Parapente",
    "Deltaplane",
    "Hélicoptère",
    "Avion léger",
    "Autre aéronef",
  ],
};

// Mapping des catégories principales et sous-catégories selon votre structure
export const CATEGORY_SUBCATEGORIES_MAP = {
  "voiture-utilitaire": ["voiture", "utilitaire", "caravane", "remorque"],
  "moto-scooter-quad": ["moto", "scooter", "quad"],
  "nautisme-sport-aerien": ["bateau", "jetski", "aerien"],
  services: ["reparation", "remorquage", "entretien", "autre-service"],
  pieces: ["piece-voiture", "piece-moto", "autre-piece"],
};

export const categories = [
  { value: "voiture-utilitaire", label: "Voitures - Utilitaires", icon: "🚗" },
  { value: "moto-scooter-quad", label: "Motos, Scooters, Quads", icon: "🏍️" },
  {
    value: "nautisme-sport-aerien",
    label: "Nautisme, Sport et Plein air",
    icon: "🚤",
  },
  { value: "services", label: "Services", icon: "🛠️" },
  { value: "pieces", label: "Pièces détachées", icon: "🔧" },
];
